# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 易趣

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "7 7-20 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【易趣】"
              run: |
                  node Task/YQ.js
              env:
                  YQNB_yqnbHEADER: ${{ secrets.YQNB_yqnbHEADER }}
                  YQNB_yqnbBODY: ${{ secrets.YQNB_yqnbBODY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  
